### ISSUE TITLE
How can I set high initial angular velocity with your code?

### ISSUE THREAD

**Issue by Pigeonisdinosaurs** [echristhuraj/CubeSatDetumblingSimulator#1]
Dear Mr. Echristhuraj,

First of all, I really appreciate for sharing this amazing matlab code.

When I set all Initial body angular velocity to 10 deg/s, the Error occured from the simulation.

I want to run the simulation with high initial angular velocicty, but I wonder what part of the code should be changed.

Once again, thank you so much.

**Comment by echristhuraj** [comment]
Hello @Pigeonisdinosaurs,

Thanks, I'm glad you found my simulator to be useful. Yes, I can confirm that you get a run-time error with high initial angular velocity rates. After some investigation, it appears that the issue stemmed from the use of Euler's method for propagation of the body angular velocity rates. While it is acceptable for propagating slow-changing state variables, the large truncation errors associated with the Euler's method make it less ideal for propagating highly nonlinear rapidly changing states, sometimes causing the stepping process to become unstable and diverge (which I believe is what caused the run-time error). The spacecraft's angular velocity has the most impact on changes to its dynamical state, so I replaced its Euler's method implementation with a higher order numerical method (Runge-Kutta 4) which appears to have resolved the issue. I have been able to successfully run scenarios with 20 deg/s on each axis, and I'm sure higher rates can be effectively simulated as well. 

The script Main.m has been updated. I think I'll close this Issue after a week or so if you feel that my revision is satisfactory; please feel free to let me know if you notice anything else that needs fixing.

EDIT: another major factor that may have contributed to the issue with high initial angular velocity rates was the fact that the sampling rate of the magnetometer was set to just 2 Hz, while the sampling rate of the gyroscope was set to 10 Hz. If the rate of change of the spacecraft's dynamic state is high at the start of the simulation, sampling at 2 Hz may not be enough for accurate observations of body-frame-relative changes in the magnetic field, and thus will lead to improper B-dot controller outputs (as both angular rates and body magnetic field measurements are used to calculate currents to the magnetorquers).
